#ifndef EFI_PROTOCOL_PATH_DEVICEPATHTOTEXT_H
#define EFI_PROTOCOL_PATH_DEVICEPATHTOTEXT_H

#include <EFI/Types.h>
#include <EFI/Protocol/Path/DevicePath.h>

#define EFI_DEVICE_PATH_TO_TEXT_PROTOCOL_GUID \
    { 0x8B843E20, 0x8132, 0x4852, { 0x90, 0xCC, 0x55, 0x1A, 0x4E, 0x4A, 0x7F, 0x1C } }

typedef struct _EFI_DEVICE_PATH_TO_TEXT_PROTOCOL {
    CHAR16* (EFIAPI* ConvertDeviceNodeToText)(IN CONST EFI_DEVICE_PATH_PROTOCOL*, IN BOOLEAN, IN BOOLEAN);
    CHAR16* (EFIAPI* ConvertDevicePathToText)(IN CONST EFI_DEVICE_PATH_PROTOCOL*, IN BOOLEAN, IN BOOLEAN);
} EFI_DEVICE_PATH_TO_TEXT_PROTOCOL;

#endif // EFI_PROTOCOL_PATH_DEVICEPATHTOTEXT_H