#ifndef EFI_PROTOCOL_TIMESTAMP_TIMESTAMP_H
#define EFI_PROTOCOL_TIMESTAMP_TIMESTAMP_H

#include <EFI/Types.h>

#define EFI_TIMESTAMP_PROTOCOL_GUID \
    { 0xAFBFDE41, 0x2E6E, 0x4262, { 0xBA, 0x65, 0x62, 0xB9, 0x23, 0x6E, 0x54, 0x95 } }

typedef struct _EFI_TIMESTAMP_PROTOCOL EFI_TIMESTAMP_PROTOCOL;

//
// EFI_TIMESTAMP_PROPERTIES
//
typedef struct {
    UINT64      Frequency;
    UINT64      EndValue;
} EFI_TIMESTAMP_PROPERTIES;

typedef
UINT64
(EFIAPI *TIMESTAMP_GET) (VOID);

typedef
EFI_STATUS
(EFIAPI *TIMESTAMP_GET_PROPERTIES) (
    OUT EFI_TIMESTAMP_PROPERTIES    *Properties
);

struct _EFI_TIMESTAMP_PROTOCOL {
    TIMESTAMP_GET               GetTimestamp;
    TIMESTAMP_GET_PROPERTIES    GetProperties;
};

#endif // EFI_PROTOCOL_TIMESTAMP_TIMESTAMP_H