#ifndef EFI_PROTOCOL_DRIVER_PLATFORMDRIVEROVERRIDE_H
#define EFI_PROTOCOL_DRIVER_PLATFORMDRIVEROVERRIDE_H

#include <EFI/Types.h>
#include <EFI/Protocol/Path/DevicePath.h>

#define EFI_PLATFORM_DRIVER_OVERRIDE_PROTOCOL_GUID \
    { 0x6B30C738, 0xA391, 0x11D4, { 0x9A, 0x3B, 0x00, 0x90, 0x27, 0x3F, 0xC1, 0x4D } }

typedef struct _EFI_PLATFORM_DRIVER_OVERRIDE_PROTOCOL EFI_PLATFORM_DRIVER_OVERRIDE_PROTOCOL;

typedef
EFI_STATUS
(EFIAPI *EFI_PLATFORM_DRIVER_OVERRIDE_GET_DRIVER) (
    IN EFI_PLATFORM_DRIVER_OVERRIDE_PROTOCOL *This,
    IN EFI_HANDLE                            ControllerHandle,
    IN OUT EFI_HANDLE                        *DriverImageHandle
);

typedef
EFI_STATUS
(EFIAPI *EFI_PLATFORM_DRIVER_OVERRIDE_GET_DRIVER_PATH) (
    IN EFI_PLATFORM_DRIVER_OVERRIDE_PROTOCOL *This,
    IN EFI_HANDLE                            ControllerHandle,
    IN OUT EFI_DEVICE_PATH_PROTOCOL          **DriverImagePath
);

typedef
EFI_STATUS
(EFIAPI *EFI_PLATFORM_DRIVER_OVERRIDE_DRIVER_LOADED) (
    IN EFI_PLATFORM_DRIVER_OVERRIDE_PROTOCOL *This,
    IN EFI_HANDLE                            ControllerHandle,
    IN EFI_DEVICE_PATH_PROTOCOL              *DriverImagePath,
    IN EFI_HANDLE                            DriverImageHandle
);

struct _EFI_PLATFORM_DRIVER_OVERRIDE_PROTOCOL {
    EFI_PLATFORM_DRIVER_OVERRIDE_GET_DRIVER      GetDriver;
    EFI_PLATFORM_DRIVER_OVERRIDE_GET_DRIVER_PATH GetDriverPath;
    EFI_PLATFORM_DRIVER_OVERRIDE_DRIVER_LOADED   DriverLoaded;
};

#endif // EFI_PROTOCOL_DRIVER_PLATFORMDRIVEROVERRIDE_H