#ifndef EFI_PROTOCOL_DRIVER_SERVICEBINDING_H
#define EFI_PROTOCOL_DRIVER_SERVICEBINDING_H

#include <EFI/Types.h>

// This protocol do not define its own GUID.

typedef struct _EFI_SERVICE_BINDING_PROTOCOL EFI_SERVICE_BINDING_PROTOCOL;


typedef
EFI_STATUS
(EFIAPI *EFI_SERVICE_BINDING_CREATE_CHILD) (
    IN EFI_SERVICE_BINDING_PROTOCOL *This,
    IN OUT EFI_HANDLE               *ChildHandle
);

typedef
EFI_STATUS
(EFIAPI *EFI_SERVICE_BINDING_DESTROY_CHILD) (
    IN EFI_SERVICE_BINDING_PROTOCOL *This,
    IN EFI_HANDLE                   ChildHandle
);

struct _EFI_SERVICE_BINDING_PROTOCOL {
    EFI_SERVICE_BINDING_CREATE_CHILD  CreateChild;
    EFI_SERVICE_BINDING_DESTROY_CHILD DestoryChild;
};

#endif // EFI_PROTOCOL_DRIVER_SERVICEBINDING_H