#ifndef EFI_PROTOCOL_DRIVER_SUPPROTEDVERSION_H
#define EFI_PROTOCOL_DRIVER_SUPPROTEDVERSION_H

#include <EFI/Types.h>

#define EFI_DRIVER_SUPPORTED_EFI_VERSION_PROTOCOL_GUID \
    { 0x5C198761, 0x16A8, 0x4E69, { 0x97, 0x2C, 0x89, 0xD6, 0x79, 0x54, 0xF8, 0x1D } }

typedef struct _EFI_DRIVER_SUPPORTED_EFI_VERSION_PROTOCOL {
    UINT32 Length;
    UINT32 FirmwareVersion;
} EFI_DRIVER_SUPPORTED_EFI_VERSION_PROTOCOL;

#endif // EFI_PROTOCOL_DRIVER_SUPPROTEDVERSION_H