#ifndef EFI_PROTOCOL_NETWORK_PXEBASECODECALLBACK_H
#define EFI_PROTOCOL_NETWORK_PXEBASECODECALLBACK_H

#include <EFI/Types.h>

#define EFI_PXE_BASE_CODE_CALLBACK_PROTOCOL_GUID \
    { 0x245DCA21, 0xFB7B, 0x11D3, { 0x8F, 0x01, 0x00, 0xA0, 0xC9, 0x69, 0x72, 0x3B } }

#define EFI_PXE_BASE_CODE_CALLBACK_PROTOCOL_REVISION    (0x00010000)

typedef struct _EFI_PXE_BASE_CODE_CALLBACK_PROTOCOL EFI_PXE_BASE_CODE_CALLBACK_PROTOCOL;

//
// EFI_PXE_BASE_CODE_CALLBACK_STATUS
//
typedef enum {
    EFI_PXE_BASE_CODE_CALLBACK_STATUS_FIRST,
    EFI_PXE_BASE_CODE_CALLBACK_STATUS_CONTINUE,
    EFI_PXE_BASE_CODE_CALLBACK_STATUS_ABORT,
    EFI_PXE_BASE_CODE_CALLBACK_STATUS_LAST
} EFI_PXE_BASE_CODE_CALLBACK_STATUS;

//
// EFI_PXE_BASE_CODE_FUNCTION
//
typedef enum {
    EFI_PXE_BASE_CODE_FUNCTION_FIRST,
    EFI_PXE_BASE_CODE_FUNCTION_DHCP,
    EFI_PXE_BASE_CODE_FUNCTION_DISCOVER,
    EFI_PXE_BASE_CODE_FUNCTION_MTFTP,
    EFI_PXE_BASE_CODE_FUNCTION_UDP_WRITE,
    EFI_PXE_BASE_CODE_FUNCTION_UDP_READ,
    EFI_PXE_BASE_CODE_FUNCTION_ARP,
    EFI_PXE_BASE_CODE_FUNCTION_IGMP,
    EFI_PXE_BASE_CODE_PXE_FUNCTION_LAST
} EFI_PXE_BASE_CODE_FUNCTION;

typedef struct _EFI_PXE_BASE_CODE_PACKET EFI_PXE_BASE_CODE_PACKET;  // defined in <EFI/Protocol/Network/PxeBaseCode.h>

typedef
EFI_PXE_BASE_CODE_CALLBACK_STATUS
(EFIAPI *EFI_PXE_CALLBACK) (
    IN EFI_PXE_BASE_CODE_CALLBACK_PROTOCOL  *This,
    IN EFI_PXE_BASE_CODE_FUNCTION           Function,
    IN BOOLEAN                              Received,
    IN UINT32                               PacketLen,
    IN EFI_PXE_BASE_CODE_PACKET             *Packet OPTIONAL
);

struct _EFI_PXE_BASE_CODE_CALLBACK_PROTOCOL {
    UINT64                  Revision;
    EFI_PXE_CALLBACK        Callback;
};

#endif // EFI_PROTOCOL_NETWORK_PXEBASECODECALLBACK_H